version: '3.8'

services:
  frontend:
    container_name: frontend-container
    image: frontend-image
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    container_name: backend-container
    image: backend-image
    build:
      context: ./backend  
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
