services:
  frontend:
    container_name: frontend-container
    image: frontend-image
    build:
      context: ./app/frontend 
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    container_name: backend-container
    image: backend-image
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
