services:
  frontend:
    container_name: frontend-container
    image: frontend-image
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - products
      - shopping-cart
      - merchandise

  products:
    container_name: products-container
    image: products-image
    build:
      context: ./products
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
