name: CI/CD Pipeline

on:
  push:
    branches:
      - server-dev
  pull_request:
    branches:
      - server-prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .env file
      run: |
        if [[ "${{ github.event_name }}" == "push" ]]; then
          if [[ "${{ github.ref }}" == "refs/heads/server-dev" ]]; then
            echo -e "BACKEND_SERVICE=${{ secrets.BACKEND_SERVICE_DEV }}\nCOMPOSE_PROJECT_NAME=${{ secrets.COMPOSE_PROJECT_NAME }}" > .env
          elif [[ "${{ github.ref }}" == "refs/heads/server-prod" ]]; then
            echo -e "BACKEND_SERVICE=${{ secrets.BACKEND_SERVICE_PROD }}\nCOMPOSE_PROJECT_NAME=${{ secrets.COMPOSE_PROJECT_NAME }}" > .env
          fi
        elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
          if [[ "${{ github.base_ref }}" == "server-dev" ]]; then
            echo -e "BACKEND_SERVICE=${{ secrets.BACKEND_SERVICE_DEV }}\nCOMPOSE_PROJECT_NAME=${{ secrets.COMPOSE_PROJECT_NAME }}" > .env
          elif [[ "${{ github.base_ref }}" == "server-prod" ]]; then
            echo -e "BACKEND_SERVICE=${{ secrets.BACKEND_SERVICE_PROD }}\nCOMPOSE_PROJECT_NAME=${{ secrets.COMPOSE_PROJECT_NAME }}" > .env
          fi
        fi

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add servers to known_hosts
      run: |
        ssh-keyscan -H 54.242.123.128 >> ~/.ssh/known_hosts || echo "Failed to add server-dev to known_hosts"
        ssh-keyscan -H 34.224.214.23 >> ~/.ssh/known_hosts || echo "Failed to add server-prod to known_hosts"

    - name: Deploy to EC2
      run: |
        SERVER_IP=""
        BRANCH_DIR=""
        
        # Determina la dirección IP y la rama según el contexto
        if [[ "${{ github.base_ref }}" == "server-dev" ]]; then
          SERVER_IP="54.242.123.128"
          BRANCH_DIR="server-dev"
        elif [[ "${{ github.base_ref }}" == "server-prod" ]]; then
          SERVER_IP="34.224.214.23"
          BRANCH_DIR="server-prod"
        fi

        # Asegúrate de que SERVER_IP no esté vacío
        if [ -z "$SERVER_IP" ]; then
          echo "Invalid branch or missing server configuration"
          exit 1
        fi
        
        # Transfiere el archivo .env al servidor correspondiente
        scp .env ubuntu@$SERVER_IP:/home/ubuntu/$BRANCH_DIR/.env
        
        # Despliega y configura el entorno en el servidor
        ssh -o StrictHostKeyChecking=no ubuntu@$SERVER_IP << EOF
          sudo usermod -aG docker \$USER
          sudo chmod 666 /var/run/docker.sock

          if ! [ -x "$(command -v docker-compose)" ]; then
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi

          # Si el directorio no existe o no es un repositorio git, clónalo
          if [ ! -d /home/ubuntu/$BRANCH_DIR/.git ]; then
            sudo rm -rf /home/ubuntu/$BRANCH_DIR
            git clone https://github.com/VictorCortez358/DevOps /home/ubuntu/$BRANCH_DIR
            cd /home/ubuntu/$BRANCH_DIR
            git checkout $BRANCH_DIR  # Asegúrate de usar la rama correcta
          else
            cd /home/ubuntu/$BRANCH_DIR && git pull origin $BRANCH_DIR
          fi

          cd /home/ubuntu/$BRANCH_DIR
          if [ -f docker-compose.yml ]; then
            docker-compose down
            docker-compose up -d --build
          else
            echo "docker-compose.yml not found"
            exit 1
          fi
        EOF
