name: CI/CD Pipeline

on:
  push:
    branches:
      - server-dev
  pull_request:
    branches:
      - server-prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install


    - name: Build Docker image
      run: docker-compose build

    - name: Run integration tests
      run: docker-compose run tests

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2 (server-dev)
      if: github.ref == 'refs/heads/server-dev'
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@54.92.132.30 << 'EOF'
          mkdir -p /home/ec2-user/server-dev
          git clone https://github.com/tu-usuario/tu-repositorio.git /home/ec2-user/server-dev || (cd /home/ec2-user/server-dev && git pull origin server-dev)
          cd /home/ec2-user/server-dev
          docker-compose down
          docker-compose up -d
        EOF

    - name: Deploy to EC2 (server-prod)
      if: github.ref == 'refs/heads/server-prod'
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@3.89.132.144 << 'EOF'
          mkdir -p /home/ec2-user/server-prod
          git clone https://github.com/tu-usuario/tu-repositorio.git /home/ec2-user/server-prod || (cd /home/ec2-user/server-prod && git pull origin server-prod)
          cd /home/ec2-user/server-prod
          docker-compose down
          docker-compose up -d
        EOF
