name: CI/CD Pipeline

on:
  push:
    branches:
      - server-dev
  pull_request:
    branches:
      - server-prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        sudo systemctl enable --now docker

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build Docker image
      run: docker-compose build

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2 (server-dev)
      if: github.ref == 'refs/heads/server-dev'
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@54.92.132.30 << 'EOF'
          # Instalar Docker y Docker Compose si no están ya instalados
          sudo apt-get update || exit 1
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common || exit 1
          curl -fsSL https://get.docker.com -o get-docker.sh || exit 1
          sudo sh get-docker.sh || exit 1
          sudo systemctl enable --now docker || exit 1

          # Instalar Docker Compose
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose || exit 1
          sudo chmod +x /usr/local/bin/docker-compose || exit 1
          
          # Clonar o actualizar el repositorio
          mkdir -p /home/ubuntu/server-dev || exit 1
          git clone https://github.com/VictorCortez358/DevOps /home/ubuntu/server-dev || (cd /home/ubuntu/server-dev && git pull origin server-dev) || exit 1
          
          # Levantar contenedores
          cd /home/ubuntu/server-dev || exit 1
          docker-compose down || exit 1
          docker-compose up -d || exit 1
        EOF

    - name: Deploy to EC2 (server-prod)
      if: github.ref == 'refs/heads/server-prod'
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.89.132.144 << 'EOF'
          # Instalar Docker y Docker Compose si no están ya instalados
          sudo apt-get update || exit 1
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common || exit 1
          curl -fsSL https://get.docker.com -o get-docker.sh || exit 1
          sudo sh get-docker.sh || exit 1
          sudo systemctl enable --now docker || exit 1

          # Instalar Docker Compose
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose || exit 1
          sudo chmod +x /usr/local/bin/docker-compose || exit 1
          
          # Clonar o actualizar el repositorio
          mkdir -p /home/ubuntu/server-prod || exit 1
          git clone https://github.com/VictorCortez358/DevOps /home/ubuntu/server-prod || (cd /home/ubuntu/server-prod && git pull origin server-prod) || exit 1
          
          # Levantar contenedores
          cd /home/ubuntu/server-prod || exit 1
          docker-compose down || exit 1
          docker-compose up -d || exit 1
        EOF
