name: CI/CD Pipeline for Dev

on:
  push:
    branches:
      - server-dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up .env file
      run: |
        echo -e "BACKEND_SERVICE=${{ secrets.BACKEND_SERVICE_DEV }}\nCOMPOSE_PROJECT_NAME=${{ secrets.COMPOSE_PROJECT_NAME }}" > .env

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install backend dependencies
      run: npm install
      working-directory: ./app/backend

    - name: Run backend tests
      run: npm test
      working-directory: ./app/backend

    - name: Install frontend dependencies
      run: npm install
      working-directory: ./app/frontend

    - name: Install Playwright browsers
      run: npx playwright install
      working-directory: ./app/frontend

    - name: Start frontend server
      run: |
        nohup npm start > frontend.log 2>&1 &
        sleep 20
      working-directory: ./app/frontend

    - name: Run frontend tests
      run: npm test
      working-directory: ./app/frontend

    - name: Install Docker and Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        sudo systemctl enable --now docker

    - name: Build Docker image
      run: docker-compose build

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known_hosts
      run: ssh-keyscan -H 54.242.123.128 >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        scp .env ubuntu@54.242.123.128:/home/ubuntu/server-dev/.env
        ssh -o StrictHostKeyChecking=no ubuntu@54.242.123.128 << EOF
          sudo usermod -aG docker \$USER
          sudo chmod 666 /var/run/docker.sock

          if ! [ -x "$(command -v docker-compose)" ]; then
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi

          if [ ! -d /home/ubuntu/server-dev/.git ]; then
            sudo rm -rf /home/ubuntu/server-dev
            git clone https://github.com/VictorCortez358/DevOps /home/ubuntu/server-dev
            cd /home/ubuntu/server-dev
            git checkout server-dev
          else
            cd /home/ubuntu/server-dev && git pull origin server-dev
          fi

          cd /home/ubuntu/server-dev
          if [ -f docker-compose.yml ]; then
            docker-compose down
            docker-compose up -d --build
          else
            echo "docker-compose.yml not found"
            exit 1
          fi
        EOF
